### ISSUE TITLE
Not showing up in Sublime Text 3.2.2 (3211)

### ISSUE THREAD

**Issue by d4rkd3v1l** [braver/XcodeColors#1]
This packages looks really promising to me. Unfortunately it doesn't show up for me in the "command palette" (cmd+shift+p) no matter if I search for Xcode, Swift, Civic, etc.

Am I doing something wrong here? I just installed it, using Sublime Text's Package Control and I can also locate it in:
~/Library/Application Support/Sublime Text 3/Installed Packages/Xcode Colors.sublime-package

Also nothing related in "preferences -> ignored packages" (only this "Vintage" thingy, which is per default there?).

Any help is highly appreciated. Thanks in advance.
Best Martin

**Comment by braver** [comment]
In the palette, first go to “change color scheme”, then you’ll get a list of color schemes you can select, they should be in there.

**Comment by d4rkd3v1l** [comment]
Oh man, didn't know about this color scheme thing. 🙈 Just thought this is some "syntax highlighting". 
THX!

So basically I just use a color scheme like this combined with any syntax highlighting for Swift, right?

**Comment by braver** [comment]
Exactly. The syntax package tells us what’s what, the color scheme package decides which color goes where.
