### ISSUE TITLE
Possible to release work in `new_colors` branch?

### ISSUE THREAD

**Issue by hovsater** [braver/XcodeColors#3]
Hey, @braver 👋 

Would it be possible to do a release of the work in the `new_colors` branch or is it still WIP?

**Comment by braver** [comment]
If you want to use it, the branch is there and you can install it manually. I started this branch a while ago, but I really want the colors to be better assigned to all the different scopes. And so it needs a bunch more work.

**Comment by hovsater** [comment]
I see, that makes sense. Thanks for letting me know. 🙂
